### ISSUE TITLE
Tab too small, only file extension

### ISSUE THREAD

**Issue by vanossj** [vanossj/tab-pair-header-source#5]
[Copied from issue 1](https://github.com/vanossj/tab-pair-header-source/issues/1#issuecomment-253626418)

> <img width="472" alt="screen shot 2016-10-13 at 1 15 30 pm" src="https://cloud.githubusercontent.com/assets/67395/19365344/28a5335c-9147-11e6-8919-3d8181cda229.png">
> 
> It could be my theme, but I'm noticing that the tabs are far too small. They aren't big enough for the `.spec.js` (perhaps because you hard-coded the width of the tab to accomodate for 1 or 2 letter file extensions?)
> 
> Do the tabs resize to fit their text or do the change size to hard-coded dimensions? Also note the fading effect (which could just be my theme not playing nicely).
> 
> This is my theme settings:
> ![image](https://cloud.githubusercontent.com/assets/67395/19365386/5b0f693e-9147-11e6-9303-b99c32b872b4.png)

**Comment by vanossj** [comment]
tabs are made smaller by setting the _max-width_ to _min-content_. I believe this should keep all text content visible, but its may vary depending on how different theses set the styles for tabs.

I tried this (UI theme)[https://atom.io/themes/atom-material-ui] and this this (Syntax theme)[https://atom.io/themes/monokai]. I think those are the ones @ProLoser used.

![image](https://cloud.githubusercontent.com/assets/8310169/19402362/bfaaeaa2-922e-11e6-9e01-93ddeac00a23.png)

![image](https://cloud.githubusercontent.com/assets/8310169/19402372/cb0cc35c-922e-11e6-8f8b-333c39a12ad1.png)

The text isn't compressed for me, but I did notice that .spec.js file is compressed to .js since technically .js is the extension.

**Comment by ProLoser** [comment]
hmm gotcha.
